### ISSUE TITLE
vx-linux icon

### ISSUE THREAD

**Issue by zen0bit** [dessington/vx-linux#1]
## Ever heard about [quickemu](https://github.com/quickemu-project/quickemu)?
 I am adding VX Linux to quickget.
[pull](https://github.com/quickemu-project/quickemu/pull/673)

Also I would like to use vx-linux icon in my gui for quickemu
 Still work in progress...

# Could you provide (prefferably SVG) but any VX Linux logo icon?

(I could use void icon but...)

### BTW: I am runnig VX-linux for some months on my main machine flawlessly... (Thank you)

**Comment by dessington** [comment]
Nice project, thanks for including VX. And I'm glad to hear it's working well for you. I've added the logo: https://github.com/dessington/vx-linux/blob/main/vxlogo-master.svg - let me know if that's suitable.

**Comment by zen0bit** [comment]
Thank you this could be closed..

**Comment by zen0bit** [comment]
And maybe something more like your VX distro logo icon?
like this...
![vxlinux](https://user-images.githubusercontent.com/6384793/224224722-52c66a19-a887-44dd-95f0-51df0b9af3f1.png)
but svg

**Comment by zen0bit** [comment]
or the one you provided but with added VX...

**Comment by dessington** [comment]
Here you go: https://github.com/dessington/vx-linux/blob/main/vxlogin.svg

**Comment by zen0bit** [comment]
thank you

PS:
I put out first public alpha version of my quickgui
check it
[repo](https://github.com/oSoWoSo/yadEmu)

See it in action...
[quickgui](https://www.youtube.com/watch?v=JtjIseqZMkQ)

if you preffer command line...
[quicktui](https://www.youtube.com/watch?v=gJ5hqYEskOw)
